// AUTH
export const GET_USER_DATA_PENDING = "GET_USER_DATA_PENDING";
export const GET_USER_DATA_FULFILLED = "GET_USER_DATA_FULFILLED";
export const GET_USER_DATA_REJECTED = "GET_USER_DATA_REJECTED";

export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_FULFILLED = "SIGNUP_FULFILLED";
export const SIGNUP_REJECTED = "SIGNUP_REJECTED";

export const CHANGE_SIGNUP_INPUT_USERNAME = "CHANGE_SIGNUP_INPUT_USERNAME";
export const CHANGE_SIGNUP_INPUT_PASSWORD = "CHANGE_SIGNUP_INPUT_PASSWORD";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const CHANGE_LOGIN_INPUT_USERNAME = "CHANGE_LOGIN_INPUT_USERNAME";
export const CHANGE_LOGIN_INPUT_PASSWORD = "CHANGE_LOGIN_INPUT_PASSWORD";

export const SIGNOUT = "SIGNOUT";

export const UPLOAD_IMAGE_PENDING = "UPLOAD_IMAGE_PENDING";
export const UPLOAD_IMAGE_FULFILLED = "UPLOAD_IMAGE_FULFILLED";
export const UPLOAD_IMAGE_REJECTED = "UPLOAD_IMAGE_REJECTED";

//TODO
export const GET_ALL_TODO_PENDING = "GET_ALL_TODO_PENDING";
export const GET_ALL_TODO_FULFILLED = "GET_ALL_TODO_FULFILLED";
export const GET_ALL_TODO_REJECTED = "GET_ALL_TODO_REJECTED";

export const CHANGE_CREATE_TODO_INPUT = "CHANGE_CREATE_TODO_INPUT";

export const CREATE_TODO_PENDING = "CREATE_TODO_PENDING";
export const CREATE_TODO_FULFILLED = "CREATE_TODO_FULFILLED";
export const CREATE_TODO_REJECTED = "CREATE_TODO_REJECTED";

export const UPDATE_TODO_PENDING = "UPDATE_TODO_PENDING";
export const UPDATE_TODO_FULFILLED = "UPDATE_TODO_FULFILLED";
export const UPDATE_TODO_REJECTED = "UPDATE_TODO_REJECTED";

export const DELETE_TODO_PENDING = "DELETE_TODO_PENDING";
export const DELETE_TODO_FULFILLED = "DELETE_TODO_FULFILLED";
export const DELETE_TODO_REJECTED = "DELETE_TODO_REJECTED";

// sort TODO
export const SORT_FROM_NEW = "SORT_FROM_NEW";
export const SORT_FROM_OLD = "SORT_FROM_OLD";
export const SORT_FROM_HOUR = "SORT_FROM_HOUR";

//POSTS
export const CHANGE_POSTS_SEARCH_INPUT = "CHANGE_POSTS_SEARCH_INPUT";

export const GET_FAKE_POSTS_PENDING = "GET_FAKE_POSTS_PENDING";
export const GET_FAKE_POSTS_FULFILLED = "GET_FAKE_POSTS_FULFILLED";
export const GET_FAKE_POSTS_REJECTED = "GET_FAKE_POSTS_REJECTED";
